#pragma once
#include <algorithm>                      
#include <any>                            
#include <array>                          
#include <atomic>                         
#include <bit>                            
#include <bitset>                         
#include <cassert>                        
#include <cctype>                         
#include <cerrno>                         
#include <cfloat>                         
#include <charconv>                       
#include <chrono>                         
#include <cinttypes>                      
#include <climits>                        
#include <clocale>                        
#include <cmath>                          
#include <codecvt>                        
#include <compare>                        
#include <concepts>                       
#include <condition_variable>             
#include <coroutine>                      
#include <csignal>                        
#include <cstddef>                        
#include <cstdint>                        
#include <cstdio>                         
#include <cstdlib>                        
#include <cstring>                        
#include <ctime>                          
#include <cuchar>                         
#include <cwchar>                         
#include <cwctype>                        
#include <deque>                          
#include <exception>                      
#include <filesystem>                     
#include <forward_list>                   
#include <fstream>                        
#include <functional>                     
#include <initializer_list>               
#include <iomanip>                        
#include <ios>                            
#include <iostream>                       
#include <istream>                        
#include <iterator>                       
#include <limits>                         
#include <list>                           
#include <locale>                         
#include <map>                            
#include <memory>                         
#include <memory_resource>                
#include <mutex>                          
#include <new>                            
#include <numeric>                        
#include <optional>                       
#include <ostream>                        
#include <random>                         
#include <set>                            
#include <span>                           
#include <sstream>                        
#include <stdexcept>                      
#include <stop_token>                     
#include <string>                         
#include <string_view>                    
#include <system_error>                   
#include <thread>                         
#include <tuple>                          
#include <type_traits>                    
#include <typeindex>                      
#include <typeinfo>                       
#include <unordered_map>                  
#include <unordered_set>                  
#include <utility>                        
#include <variant>                        
#include <vector>                         
#include <version>                        
#if __has_include(<source_location>)
# include <source_location>               
#elif __has_include(<experimental/source_location>)
# include <experimental/source_location>  
# if __cpp_lib_experimental_source_location
namespace std {
using experimental::source_location;
} // namespace std
# endif
#endif
